# Generated by Django 3.1.4 on 2020-12-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookissue',
            table='tbl_book_issue_table',
        ),
        migrations.AlterModelTable(
            name='books',
            table='tbl_books_table',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='tbl_profile_table',
        ),
        migrations.AlterModelTable(
            name='role',
            table='tbl_role_table',
        ),
    ]
